import os

SUPORTED_TAGS = {
        'a': ['href' ,'id', 'name'],
        'b': ['id'],
        'big': [],
        'blockquote': ['id'],
        'body': [],
        'br': ['id'],
        'center': [],
        'cite': [],
        'dd': ['id', 'title'],
        'del': [],
        'dfn': [],
        'div': ['align', 'id', 'bgcolor'],
        'em': ['id', 'title'],
        'font': ['color', 'face', 'id', 'size'],
        'head': [],
        'h1': [],
        'h2': [],
        'h3': [],
        'h4': [],
        'h5': [],
        'h6': [],
        'hr /': ['color', 'id', 'width'],
        'html': [],
        'i': ['class', 'id'],
        'img /': ['align', 'border', 'height', 'id', 'src', 'width'],
        'li': ['class', 'id', 'title'],
        'ol': ['id'],
        'p': ['align', 'id', 'title'],
        's': ['id', 'style', 'title'],
        'small': ['id'],
        'span': ['bgcolor', 'title'],
        'strike': ['class', 'id'],
        'strong': ['class', 'id'],
        'sub': ['id'],
        'sup': ['class', 'id'],
        'u': ['id'],
        'ul': ['class', 'id'],
        'var': []
        }
BASE_DIR = os.path.dirname(os.path.realpath(__file__))
EPUB_TEMPLATES_DIR = os.path.join(BASE_DIR, 'epub_templates')